### PR TITLE
DLS-9710: Improve Session/request ID Logging

### PR DESCRIPTION
**Pull request by johno1985**

### CODE REVIEW

**Review by TomRafferty — DISMISSED** [review]

**Comment by karolina-zaborska** [comment]
When run locally 18 tests in uk.gov.hmrc.helptosaveapi.services.HelpToSaveApiServiceSpec failed. How does it look like on your machine?

**Comment by mahesh-hmrc** [comment]
Same here, have `HelpToSaveApiServiceSpec` failing on how the mocks are setup. However, can see that the PR builder one has gone through fine.

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
@karolina-zaborska @mahesh-hmrc please can you both check which version of java is being used on your local machine to build this? We should be using:

**Comment by johno1985** [comment]
Have re-run the PR builder and it still passes

**Comment by karolina-zaborska** [comment]
> @karolina-zaborska @mahesh-hmrc please can you both check which version of java is being used on your local machine to build this? We should be using: openjdk version "11.0.21" 2023-10-17 OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9) OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)

I've been using 11.0.2, changed to 11.0.22 and all of the tests passed locally. Approve!

**Pull request merged**
